import type { MenuItem, InventoryItem } from '@/types/loyolas'

export const CATEGORIES = [
  'Carnes',
  'Frango',
  'Hot-Dog',
  'Gourmet',
  'Especial',
  'Combos',
  'Bebidas',
  'Complementos',
] as const
export const UNITS = ['un', 'porção', 'fatia', 'rolo', 'g', 'kg', 'ml', 'l'] as const
export const PAYMENTS = ['Dinheiro', 'Pix', 'Cartão'] as const
export const GROUPS = ['Ingrediente', 'Operacional'] as const

export const fmtBRL = (n: number | string | undefined | null) =>
  (Number(n) || 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })

export const padTicket = (n: number | string | undefined | null) =>
  `#${String(n ?? 0).padStart(4, '0')}`

export const uid = (p: string) =>
  `${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 7)}`

const R: Record<string, string> = {
  pao: 'ing-pao',
  paofr: 'ing-pao-frances',
  hamb: 'ing-hamburguer',
  contrafile: 'ing-contrafile',
  gourmet: 'ing-carne-gourmet',
  maxcarne: 'ing-carne-max',
  apres: 'ing-apresuntado',
  queijo: 'ing-queijo',
  cheddar: 'ing-cheddar',
  catupiry: 'ing-catupiry',
  ovo: 'ing-ovo',
  bacon: 'ing-bacon',
  calabresa: 'ing-calabresa',
  linguica: 'ing-linguica',
  filefrango: 'ing-file-frango',
  frangodesf: 'ing-frango-desfiado',
  salsicha: 'ing-salsicha',
  brocolis: 'ing-brocolis',
  maionese: 'ing-maionese',
  ketchup: 'ing-ketchup',
  mostarda: 'ing-mostarda',
  palha: 'ing-batata-palha',
  molho: 'ing-molho',
  vinagrete: 'ing-vinagrete',
  alface: 'ing-alface',
  cebola: 'ing-cebola',
  tomate: 'ing-tomate',
  milho: 'ing-milho',
  maionesecasa: 'ing-maionese-casa',
  batata300: 'ing-batata-300',
  refrilata: 'ing-refri-lata',
  refri600: 'ing-refri-600',
  refri1l: 'ing-refri-1l',
  refri2l: 'ing-refri-2l',
  refri200: 'ing-refri-200',
  suco: 'ing-suco',
  agua500: 'ing-agua-500',
}

export function rec(...keys: string[]) {
  const map: Record<string, number> = {}
  keys.forEach((k) => {
    if (k === 'molho') {
      ;['ing-maionese', 'ing-ketchup', 'ing-mostarda', 'ing-batata-palha'].forEach((id) => {
        map[id] = (map[id] || 0) + 1
      })
    } else {
      const id = R[k]
      if (id) map[id] = (map[id] || 0) + 1
    }
  })
  return Object.entries(map).map(([ingredientId, qty]) => ({ ingredientId, qty }))
}

const mk = (
  code: string,
  name: string,
  price: number,
  category: MenuItem['category'],
  recipe: { ingredientId: string; qty: number }[],
): Omit<MenuItem, 'id'> & { code: string } => ({
  code,
  name,
  price,
  category,
  active: true,
  recipe,
})

const ing = (
  code: string,
  name: string,
  unit: InventoryItem['unit'],
  qty: number,
  min: number,
  group: InventoryItem['group'],
): Omit<InventoryItem, 'id'> & { code: string } => ({
  code,
  name,
  unit,
  qty,
  min,
  group,
})

export const seedStock = (): (Omit<InventoryItem, 'id'> & { code: string })[] => [
  ing('ing-pao', 'Pão de Hambúrguer', 'un', 80, 20, 'Ingrediente'),
  ing('ing-pao-frances', 'Pão Francês', 'un', 60, 15, 'Ingrediente'),
  ing('ing-hamburguer', 'Hambúrguer (carne bovina)', 'un', 60, 15, 'Ingrediente'),
  ing('ing-contrafile', 'Contra-Filé', 'un', 30, 8, 'Ingrediente'),
  ing('ing-carne-gourmet', 'Carne Gourmet', 'un', 30, 8, 'Ingrediente'),
  ing('ing-carne-max', 'Carne Max', 'un', 20, 5, 'Ingrediente'),
  ing('ing-apresuntado', 'Presunto / Apresuntado', 'fatia', 120, 30, 'Ingrediente'),
  ing('ing-queijo', 'Queijo Mussarela', 'fatia', 120, 30, 'Ingrediente'),
  ing('ing-cheddar', 'Cheddar', 'porção', 40, 10, 'Ingrediente'),
  ing('ing-catupiry', 'Catupiry', 'porção', 40, 10, 'Ingrediente'),
  ing('ing-ovo', 'Ovo', 'un', 60, 15, 'Ingrediente'),
  ing('ing-bacon', 'Bacon', 'porção', 50, 12, 'Ingrediente'),
  ing('ing-calabresa', 'Calabresa', 'porção', 50, 12, 'Ingrediente'),
  ing('ing-linguica', 'Linguiça', 'un', 20, 5, 'Ingrediente'),
  ing('ing-file-frango', 'Filé de Frango', 'un', 30, 8, 'Ingrediente'),
  ing('ing-frango-desfiado', 'Frango Desfiado', 'porção', 30, 8, 'Ingrediente'),
  ing('ing-salsicha', 'Salsicha', 'un', 40, 10, 'Ingrediente'),
  ing('ing-brocolis', 'Brócolis', 'porção', 15, 4, 'Ingrediente'),
  ing('ing-maionese', 'Maionese', 'porção', 80, 20, 'Ingrediente'),
  ing('ing-ketchup', 'Ketchup', 'porção', 80, 20, 'Ingrediente'),
  ing('ing-mostarda', 'Mostarda', 'porção', 80, 20, 'Ingrediente'),
  ing('ing-batata-palha', 'Batata Palha', 'porção', 80, 20, 'Ingrediente'),
  ing('ing-alface', 'Alface', 'porção', 60, 15, 'Ingrediente'),
  ing('ing-cebola', 'Cebola', 'porção', 60, 15, 'Ingrediente'),
  ing('ing-tomate', 'Tomate', 'porção', 60, 15, 'Ingrediente'),
  ing('ing-milho', 'Milho', 'porção', 60, 15, 'Ingrediente'),
  ing('ing-vinagrete', 'Vinagrete', 'porção', 15, 4, 'Ingrediente'),
  ing('ing-maionese-casa', 'Maionese da Casa', 'porção', 15, 4, 'Ingrediente'),
  ing('ing-batata-300', 'Batata Frita de 300g', 'kg', 30, 8, 'Ingrediente'),
  ing('ing-refri-lata', 'Refrigerante Lata', 'un', 48, 12, 'Ingrediente'),
  ing('ing-refri-600', 'Refrigerante 600ml', 'un', 24, 6, 'Ingrediente'),
  ing('ing-refri-1l', 'Refrigerante 1L', 'un', 18, 5, 'Ingrediente'),
  ing('ing-refri-2l', 'Refrigerante 2L', 'un', 12, 4, 'Ingrediente'),
  ing('ing-refri-200', 'Refrigerante 200ml', 'un', 20, 5, 'Ingrediente'),
  ing('ing-suco', 'Suco Tropical', 'un', 20, 5, 'Ingrediente'),
  ing('ing-agua-500', 'Água Mineral 500ml', 'un', 24, 6, 'Ingrediente'),
  ing('ing-hamburgueira', 'Hamburgueira (equipamento)', 'un', 2, 1, 'Operacional'),
  ing('ing-papel-toalha', 'Papel Toalha', 'rolo', 10, 3, 'Operacional'),
  ing('ing-filme-pvc', 'Plástico Filme PVC', 'rolo', 6, 2, 'Operacional'),
  ing('ing-tempero', 'Tempero', 'un', 15, 4, 'Operacional'),
  ing('ing-caneta', 'Caneta', 'un', 8, 2, 'Operacional'),
  ing('ing-saquinho', 'Saquinho de Lanche', 'un', 300, 60, 'Operacional'),
  ing('ing-sacola', 'Sacola', 'un', 200, 40, 'Operacional'),
  ing('ing-touca', 'Touca Descartável', 'un', 100, 20, 'Operacional'),
  ing('ing-sache-ketchup', 'Sachê de Ketchup', 'un', 200, 40, 'Operacional'),
  ing('ing-sache-mostarda', 'Sachê de Mostarda', 'un', 200, 40, 'Operacional'),
  ing('ing-sache-maionese', 'Sachê de Maionese', 'un', 200, 40, 'Operacional'),
  ing('ing-sache-extra', 'Sachê Extra', 'un', 200, 40, 'Operacional'),
  ing('ing-palito', 'Palito', 'un', 500, 100, 'Operacional'),
  ing('ing-guardanapos', 'Guardanapos', 'un', 300, 50, 'Operacional'),
]

export const seedMenu = (): (Omit<MenuItem, 'id'> & { code: string })[] => [
  mk(
    'c-hamburguer',
    'Hambúrguer',
    15,
    'Carnes',
    rec('pao', 'hamb', 'apres', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
  ),
  mk(
    'c-americano',
    'Americano',
    16,
    'Carnes',
    rec('pao', 'apres', 'queijo', 'ovo', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
  ),
  mk('c-misto', 'Misto Quente', 13, 'Carnes', rec('pao', 'apres', 'queijo', 'molho')),
  mk(
    'c-bauru',
    'Bauru',
    15,
    'Carnes',
    rec('pao', 'apres', 'queijo', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
  ),
  mk('c-xburguer', 'X-Burguer', 15, 'Carnes', rec('pao', 'hamb', 'apres', 'queijo', 'molho')),
  mk(
    'c-xsalada',
    'X-Salada',
    17,
    'Carnes',
    rec('pao', 'hamb', 'apres', 'queijo', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
  ),
  mk(
    'c-xegg',
    'X-Egg',
    19,
    'Carnes',
    rec('pao', 'hamb', 'apres', 'ovo', 'queijo', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
  ),
  mk(
    'c-xcalabresa',
    'X-Calabresa',
    24,
    'Carnes',
    rec(
      'pao',
      'hamb',
      'apres',
      'calabresa',
      'queijo',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'c-xcalabresaegg',
    'X-Calabresa Egg',
    24.5,
    'Carnes',
    rec(
      'pao',
      'hamb',
      'apres',
      'calabresa',
      'ovo',
      'queijo',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'c-xbacon',
    'X-Bacon',
    24,
    'Carnes',
    rec('pao', 'hamb', 'apres', 'bacon', 'queijo', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
  ),
  mk(
    'c-xbaconegg',
    'X-Bacon Egg',
    24.5,
    'Carnes',
    rec(
      'pao',
      'hamb',
      'apres',
      'bacon',
      'ovo',
      'queijo',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'c-xtudo',
    'X-Tudo',
    26,
    'Carnes',
    rec(
      'pao',
      'hamb',
      'apres',
      'bacon',
      'queijo',
      'ovo',
      'calabresa',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'c-contrafile',
    'Contra-Filé',
    23,
    'Carnes',
    rec('pao', 'contrafile', 'apres', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
  ),
  mk(
    'c-xcontrafile',
    'X-Contra-Filé',
    25,
    'Carnes',
    rec('pao', 'contrafile', 'apres', 'queijo', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
  ),
  mk(
    'c-xcontrafileegg',
    'X-Contra-Filé Egg',
    27,
    'Carnes',
    rec(
      'pao',
      'contrafile',
      'apres',
      'queijo',
      'ovo',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'c-xcontrafilecalabresa',
    'X-Contra-Filé Calabresa',
    29,
    'Carnes',
    rec(
      'pao',
      'contrafile',
      'apres',
      'queijo',
      'calabresa',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'c-xcontrafilebacon',
    'X-Contra-Filé Bacon',
    29,
    'Carnes',
    rec(
      'pao',
      'contrafile',
      'apres',
      'queijo',
      'bacon',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'c-xcontrafilecalabresaegg',
    'X-Contra-Filé Calabresa Egg',
    29.5,
    'Carnes',
    rec(
      'pao',
      'contrafile',
      'apres',
      'queijo',
      'calabresa',
      'ovo',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'c-xcontrafilebaconegg',
    'X-Contra-Filé Bacon Egg',
    29.5,
    'Carnes',
    rec(
      'pao',
      'contrafile',
      'apres',
      'queijo',
      'bacon',
      'ovo',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'c-xcontrafiletudo',
    'X-Contra-Filé Tudo',
    32,
    'Carnes',
    rec(
      'pao',
      'contrafile',
      'apres',
      'queijo',
      'calabresa',
      'bacon',
      'ovo',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'c-max',
    'Max',
    21,
    'Carnes',
    rec('pao', 'apres', 'maxcarne', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
  ),
  mk(
    'c-xmax',
    'X Max',
    22,
    'Carnes',
    rec('pao', 'apres', 'maxcarne', 'queijo', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
  ),
  mk(
    'c-xmaxegg',
    'X Max Egg',
    23,
    'Carnes',
    rec(
      'pao',
      'apres',
      'maxcarne',
      'queijo',
      'ovo',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'c-xmaxcalabresa',
    'X Max Calabresa',
    27,
    'Carnes',
    rec(
      'pao',
      'apres',
      'maxcarne',
      'queijo',
      'calabresa',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'c-xmaxbacon',
    'X Max Bacon',
    27,
    'Carnes',
    rec(
      'pao',
      'apres',
      'maxcarne',
      'queijo',
      'bacon',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'c-xmaxcalabresaegg',
    'X Max Calabresa Egg',
    27.5,
    'Carnes',
    rec(
      'pao',
      'apres',
      'maxcarne',
      'queijo',
      'calabresa',
      'ovo',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'c-xmaxbaconegg',
    'X Max Bacon Egg',
    27.5,
    'Carnes',
    rec(
      'pao',
      'apres',
      'maxcarne',
      'queijo',
      'bacon',
      'ovo',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'c-xmaxtudo',
    'X Max Tudo',
    30,
    'Carnes',
    rec(
      'pao',
      'apres',
      'maxcarne',
      'queijo',
      'bacon',
      'calabresa',
      'ovo',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'f-file',
    'Filé',
    21,
    'Frango',
    rec('pao', 'filefrango', 'apres', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
  ),
  mk(
    'f-xfile',
    'X-Filé',
    22,
    'Frango',
    rec('pao', 'filefrango', 'apres', 'queijo', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
  ),
  mk(
    'f-xfileegg',
    'X-Filé Egg',
    23,
    'Frango',
    rec(
      'pao',
      'filefrango',
      'apres',
      'queijo',
      'ovo',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'f-xfilecalabresa',
    'X-Filé Calabresa',
    27,
    'Frango',
    rec(
      'pao',
      'filefrango',
      'apres',
      'queijo',
      'calabresa',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'f-xfilecalabresaegg',
    'X-Filé Calabresa Egg',
    27.5,
    'Frango',
    rec(
      'pao',
      'filefrango',
      'apres',
      'queijo',
      'calabresa',
      'ovo',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'f-xfilebacon',
    'X-Filé Bacon',
    27,
    'Frango',
    rec(
      'pao',
      'filefrango',
      'apres',
      'queijo',
      'bacon',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'f-xfilebaconegg',
    'X-Filé Bacon Egg',
    27.5,
    'Frango',
    rec(
      'pao',
      'filefrango',
      'apres',
      'queijo',
      'bacon',
      'ovo',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'f-xfiletudo',
    'X-Filé Tudo',
    29,
    'Frango',
    rec(
      'pao',
      'filefrango',
      'apres',
      'bacon',
      'queijo',
      'ovo',
      'calabresa',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'f-carijo',
    'Carijó',
    21,
    'Frango',
    rec('pao', 'frangodesf', 'apres', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
  ),
  mk(
    'f-xcarijo',
    'X-Carijó',
    23,
    'Frango',
    rec('pao', 'frangodesf', 'apres', 'queijo', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
  ),
  mk(
    'f-xcarijoegg',
    'X-Carijó Egg',
    23,
    'Frango',
    rec(
      'pao',
      'frangodesf',
      'apres',
      'queijo',
      'ovo',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'f-xcarijocalabresa',
    'X-Carijó Calabresa',
    27,
    'Frango',
    rec(
      'pao',
      'frangodesf',
      'apres',
      'queijo',
      'calabresa',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'f-xcarijocalabresaegg',
    'X-Carijó Calabresa Egg',
    27.5,
    'Frango',
    rec(
      'pao',
      'frangodesf',
      'apres',
      'queijo',
      'calabresa',
      'ovo',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'f-xcarijobacon',
    'X-Carijó Bacon',
    27,
    'Frango',
    rec(
      'pao',
      'frangodesf',
      'apres',
      'queijo',
      'bacon',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'f-xcarijobaconegg',
    'X-Carijó Bacon Egg',
    27.5,
    'Frango',
    rec(
      'pao',
      'frangodesf',
      'apres',
      'queijo',
      'bacon',
      'ovo',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'f-xcarijotudo',
    'X-Carijó Tudo',
    29,
    'Frango',
    rec(
      'pao',
      'frangodesf',
      'apres',
      'queijo',
      'bacon',
      'ovo',
      'calabresa',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'h-hotdog',
    'Hotdog',
    15,
    'Hot-Dog',
    rec('pao', 'salsicha', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
  ),
  mk(
    'h-xhotdog',
    'X-Hotdog',
    17,
    'Hot-Dog',
    rec('pao', 'salsicha', 'queijo', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
  ),
  mk(
    'h-xhotdogegg',
    'X-Hotdog Egg',
    19,
    'Hot-Dog',
    rec('pao', 'salsicha', 'queijo', 'ovo', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
  ),
  mk(
    'h-xhotdogbacon',
    'X-Hotdog Bacon',
    24,
    'Hot-Dog',
    rec('pao', 'salsicha', 'bacon', 'queijo', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
  ),
  mk(
    'h-xhotdogbaconegg',
    'X-Hotdog Bacon Egg',
    24.5,
    'Hot-Dog',
    rec(
      'pao',
      'salsicha',
      'bacon',
      'ovo',
      'queijo',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'h-xhotdogcalabresa',
    'X-Hotdog Calabresa',
    24,
    'Hot-Dog',
    rec('pao', 'salsicha', 'calabresa', 'queijo', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
  ),
  mk(
    'h-xhotdogcalabresaegg',
    'X-Hotdog Calabresa Egg',
    24.5,
    'Hot-Dog',
    rec(
      'pao',
      'salsicha',
      'calabresa',
      'ovo',
      'queijo',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'h-xhotdogtudo',
    'X-Hotdog Tudo',
    26,
    'Hot-Dog',
    rec(
      'pao',
      'salsicha',
      'bacon',
      'ovo',
      'calabresa',
      'queijo',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'g-hamburguergourmet',
    'Hambúrguer Gourmet',
    22,
    'Gourmet',
    rec('pao', 'gourmet', 'apres', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
  ),
  mk(
    'g-xburguergourmet',
    'X-Burguer Gourmet',
    22,
    'Gourmet',
    rec('pao', 'gourmet', 'apres', 'queijo', 'molho'),
  ),
  mk(
    'g-xsaladagourmet',
    'X-Salada Gourmet',
    24,
    'Gourmet',
    rec('pao', 'gourmet', 'apres', 'queijo', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
  ),
  mk(
    'g-xegggourmet',
    'X-Egg Gourmet',
    26,
    'Gourmet',
    rec('pao', 'gourmet', 'apres', 'ovo', 'queijo', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
  ),
  mk(
    'g-xcalabresagourmet',
    'X-Calabresa Gourmet',
    29,
    'Gourmet',
    rec(
      'pao',
      'gourmet',
      'apres',
      'calabresa',
      'queijo',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'g-xcalabresaegggourmet',
    'X-Calabresa Egg Gourmet',
    29.5,
    'Gourmet',
    rec(
      'pao',
      'gourmet',
      'apres',
      'calabresa',
      'ovo',
      'queijo',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'g-xbacongourmet',
    'X-Bacon Gourmet',
    29,
    'Gourmet',
    rec(
      'pao',
      'gourmet',
      'apres',
      'bacon',
      'queijo',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'g-xbaconegggourmet',
    'X-Bacon Egg Gourmet',
    29.5,
    'Gourmet',
    rec(
      'pao',
      'gourmet',
      'apres',
      'bacon',
      'ovo',
      'queijo',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'g-xtudogourmet',
    'X-Tudo Gourmet',
    32,
    'Gourmet',
    rec(
      'pao',
      'gourmet',
      'apres',
      'bacon',
      'queijo',
      'ovo',
      'calabresa',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'e-especialgourmet',
    'Especial Gourmet',
    45,
    'Gourmet',
    rec(
      'pao',
      'gourmet',
      'gourmet',
      'apres',
      'queijo',
      'queijo',
      'bacon',
      'ovo',
      'ovo',
      'calabresa',
      'catupiry',
      'cheddar',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'e-xbrocolis',
    'X-Brócolis (com Bacon)',
    24,
    'Especial',
    rec('pao', 'bacon', 'brocolis', 'queijo', 'catupiry', 'molho'),
  ),
  mk(
    'h-paolinguica',
    'Pão c/ Linguiça',
    22,
    'Especial',
    rec(
      'pao',
      'linguica',
      'linguica',
      'queijo',
      'maionesecasa',
      'vinagrete',
      'alface',
      'cebola',
      'tomate',
      'milho',
    ),
  ),
  mk(
    'combo-ind1',
    'Combo Individual 01 — X-Tudo + Batata + Refri Lata',
    50,
    'Combos',
    rec(
      'pao',
      'hamb',
      'apres',
      'bacon',
      'queijo',
      'ovo',
      'calabresa',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
      'batata300',
      'refrilata',
    ),
  ),
  mk(
    'combo-ind2',
    'Combo Individual 02 — X-Bacon + Batata + Refri Lata',
    49,
    'Combos',
    rec(
      'pao',
      'hamb',
      'apres',
      'bacon',
      'queijo',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
      'batata300',
      'refrilata',
    ),
  ),
  mk(
    'combo-casal1',
    'Combo Casal 01 — 2 X-Tudo + Batata + Refri 1L',
    75,
    'Combos',
    rec(
      'pao',
      'pao',
      'hamb',
      'hamb',
      'apres',
      'apres',
      'bacon',
      'bacon',
      'queijo',
      'queijo',
      'ovo',
      'ovo',
      'calabresa',
      'calabresa',
      'molho',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
      'alface',
      'cebola',
      'tomate',
      'milho',
      'batata300',
      'refri1l',
    ),
  ),
  mk(
    'combo-casal2',
    'Combo Casal 02 — 2 X-Bacon + Batata + Refri 1L',
    73,
    'Combos',
    rec(
      'pao',
      'pao',
      'hamb',
      'hamb',
      'apres',
      'apres',
      'bacon',
      'bacon',
      'queijo',
      'queijo',
      'molho',
      'molho',
      'alface',
      'cebola',
      'tomate',
      'milho',
      'alface',
      'cebola',
      'tomate',
      'milho',
      'batata300',
      'refri1l',
    ),
  ),
  mk(
    'combo-infantil',
    'Combo Infantil — X-Burguer + Batata + Refri 200ml',
    33,
    'Combos',
    rec('pao', 'hamb', 'apres', 'queijo', 'molho', 'batata300', 'refri200'),
  ),
  mk('b-refri2l', 'Refrigerante 2L (genérico)', 10, 'Bebidas', rec('refri2l')),
  mk(
    'b-refri2lmarca',
    'Refrigerante 2L (Coca, Fanta, Sprite, Antártica)',
    15,
    'Bebidas',
    rec('refri2l'),
  ),
  mk('b-refri600', 'Refrigerante 600ml', 8, 'Bebidas', rec('refri600')),
  mk('b-refri1l', 'Refrigerante 1L', 10, 'Bebidas', rec('refri1l')),
  mk('b-refrilata', 'Refrigerante Lata', 6, 'Bebidas', rec('refrilata')),
  mk('b-suco', 'Suco Tropical', 8, 'Bebidas', rec('suco')),
  mk('b-agua500', 'Água Mineral 500ml', 3, 'Bebidas', rec('agua500')),
  mk('x-catupiry', 'Catupiry (adicional)', 4, 'Complementos', rec('catupiry')),
  mk('x-cheddar', 'Cheddar (adicional)', 3, 'Complementos', rec('cheddar')),
  mk('x-ovo', 'Ovo (adicional)', 3, 'Complementos', rec('ovo')),
  mk('x-queijo', 'Queijo (adicional)', 4, 'Complementos', rec('queijo')),
  mk('x-presunto', 'Presunto (adicional)', 3, 'Complementos', rec('apres')),
  mk('x-filefrango', 'Filé de Frango (adicional)', 10, 'Complementos', rec('filefrango')),
  mk('x-frangodesf', 'Frango Desfiado (adicional)', 10, 'Complementos', rec('frangodesf')),
  mk('x-carne', 'Carne (adicional)', 3, 'Complementos', rec('hamb')),
  mk('x-contrafile', 'Contra-Filé (adicional)', 10, 'Complementos', rec('contrafile')),
  mk('x-carnegourmet', 'Carne Gourmet (adicional)', 10, 'Complementos', rec('gourmet')),
  mk('x-paofrances', 'Pão Francês (unidade)', 2, 'Complementos', rec('paofr')),
]
