migrate(
  (app) => {
    // 1. Seed user admin
    const users = app.findCollectionByNameOrId('_pb_users_auth_')
    try {
      app.findAuthRecordByEmail('_pb_users_auth_', 'marcos.vframos@gmail.com')
    } catch (_) {
      const record = new Record(users)
      record.setEmail('marcos.vframos@gmail.com')
      record.setPassword('Skip@Pass')
      record.setVerified(true)
      record.set('name', "Loyola's Admin")
      app.save(record)
    }

    // 2. Seed settings
    const settingsCol = app.findCollectionByNameOrId('settings')
    const defaultSettings = [
      { key: 'store_name', value: "Loyola's Lanches" },
      { key: 'is_open', value: 'true' },
      { key: 'ticket_counter', value: '1' },
      { key: 'store_cnpj', value: '' },
      { key: 'store_phone', value: '(12) 99159-1915' },
      {
        key: 'store_address',
        value: 'Av. Nicanor Ramos Nogueira, Araretama, Pindamonhangaba - SP',
      },
    ]
    defaultSettings.forEach((s) => {
      try {
        app.findFirstRecordByData('settings', 'key', s.key)
      } catch (_) {
        const rec = new Record(settingsCol)
        rec.set('key', s.key)
        rec.set('value', s.value)
        app.save(rec)
      }
    })

    // 3. Seed Inventory (com insumos individuais e operacionais)
    const inventoryCol = app.findCollectionByNameOrId('inventory')
    const stockItems = [
      {
        code: 'ing-pao',
        name: 'Pão de Hambúrguer',
        unit: 'un',
        qty: 80,
        min: 20,
        group: 'Ingrediente',
      },
      {
        code: 'ing-pao-frances',
        name: 'Pão Francês',
        unit: 'un',
        qty: 60,
        min: 15,
        group: 'Ingrediente',
      },
      {
        code: 'ing-hamburguer',
        name: 'Hambúrguer (carne bovina)',
        unit: 'un',
        qty: 60,
        min: 15,
        group: 'Ingrediente',
      },
      {
        code: 'ing-contrafile',
        name: 'Contra-Filé',
        unit: 'un',
        qty: 30,
        min: 8,
        group: 'Ingrediente',
      },
      {
        code: 'ing-carne-gourmet',
        name: 'Carne Gourmet',
        unit: 'un',
        qty: 30,
        min: 8,
        group: 'Ingrediente',
      },
      {
        code: 'ing-carne-max',
        name: 'Carne Max',
        unit: 'un',
        qty: 20,
        min: 5,
        group: 'Ingrediente',
      },
      {
        code: 'ing-apresuntado',
        name: 'Presunto / Apresuntado',
        unit: 'fatia',
        qty: 120,
        min: 30,
        group: 'Ingrediente',
      },
      {
        code: 'ing-queijo',
        name: 'Queijo Mussarela',
        unit: 'fatia',
        qty: 120,
        min: 30,
        group: 'Ingrediente',
      },
      {
        code: 'ing-cheddar',
        name: 'Cheddar',
        unit: 'porção',
        qty: 40,
        min: 10,
        group: 'Ingrediente',
      },
      {
        code: 'ing-catupiry',
        name: 'Catupiry',
        unit: 'porção',
        qty: 40,
        min: 10,
        group: 'Ingrediente',
      },
      { code: 'ing-ovo', name: 'Ovo', unit: 'un', qty: 60, min: 15, group: 'Ingrediente' },
      { code: 'ing-bacon', name: 'Bacon', unit: 'porção', qty: 50, min: 12, group: 'Ingrediente' },
      {
        code: 'ing-calabresa',
        name: 'Calabresa',
        unit: 'porção',
        qty: 50,
        min: 12,
        group: 'Ingrediente',
      },
      { code: 'ing-linguica', name: 'Linguiça', unit: 'un', qty: 20, min: 5, group: 'Ingrediente' },
      {
        code: 'ing-file-frango',
        name: 'Filé de Frango',
        unit: 'un',
        qty: 30,
        min: 8,
        group: 'Ingrediente',
      },
      {
        code: 'ing-frango-desfiado',
        name: 'Frango Desfiado',
        unit: 'porção',
        qty: 30,
        min: 8,
        group: 'Ingrediente',
      },
      {
        code: 'ing-salsicha',
        name: 'Salsicha',
        unit: 'un',
        qty: 40,
        min: 10,
        group: 'Ingrediente',
      },
      {
        code: 'ing-brocolis',
        name: 'Brócolis',
        unit: 'porção',
        qty: 15,
        min: 4,
        group: 'Ingrediente',
      },
      {
        code: 'ing-maionese',
        name: 'Maionese',
        unit: 'porção',
        qty: 80,
        min: 20,
        group: 'Ingrediente',
      },
      {
        code: 'ing-ketchup',
        name: 'Ketchup',
        unit: 'porção',
        qty: 80,
        min: 20,
        group: 'Ingrediente',
      },
      {
        code: 'ing-mostarda',
        name: 'Mostarda',
        unit: 'porção',
        qty: 80,
        min: 20,
        group: 'Ingrediente',
      },
      {
        code: 'ing-batata-palha',
        name: 'Batata Palha',
        unit: 'porção',
        qty: 80,
        min: 20,
        group: 'Ingrediente',
      },
      {
        code: 'ing-alface',
        name: 'Alface',
        unit: 'porção',
        qty: 60,
        min: 15,
        group: 'Ingrediente',
      },
      {
        code: 'ing-cebola',
        name: 'Cebola',
        unit: 'porção',
        qty: 60,
        min: 15,
        group: 'Ingrediente',
      },
      {
        code: 'ing-tomate',
        name: 'Tomate',
        unit: 'porção',
        qty: 60,
        min: 15,
        group: 'Ingrediente',
      },
      { code: 'ing-milho', name: 'Milho', unit: 'porção', qty: 60, min: 15, group: 'Ingrediente' },
      {
        code: 'ing-vinagrete',
        name: 'Vinagrete',
        unit: 'porção',
        qty: 15,
        min: 4,
        group: 'Ingrediente',
      },
      {
        code: 'ing-maionese-casa',
        name: 'Maionese da Casa',
        unit: 'porção',
        qty: 15,
        min: 4,
        group: 'Ingrediente',
      },
      {
        code: 'ing-batata-300',
        name: 'Batata Frita de 300g',
        unit: 'kg',
        qty: 30,
        min: 8,
        group: 'Ingrediente',
      },
      {
        code: 'ing-refri-lata',
        name: 'Refrigerante Lata',
        unit: 'un',
        qty: 48,
        min: 12,
        group: 'Ingrediente',
      },
      {
        code: 'ing-refri-600',
        name: 'Refrigerante 600ml',
        unit: 'un',
        qty: 24,
        min: 6,
        group: 'Ingrediente',
      },
      {
        code: 'ing-refri-1l',
        name: 'Refrigerante 1L',
        unit: 'un',
        qty: 18,
        min: 5,
        group: 'Ingrediente',
      },
      {
        code: 'ing-refri-2l',
        name: 'Refrigerante 2L',
        unit: 'un',
        qty: 12,
        min: 4,
        group: 'Ingrediente',
      },
      {
        code: 'ing-refri-200',
        name: 'Refrigerante 200ml',
        unit: 'un',
        qty: 20,
        min: 5,
        group: 'Ingrediente',
      },
      {
        code: 'ing-suco',
        name: 'Suco Tropical',
        unit: 'un',
        qty: 20,
        min: 5,
        group: 'Ingrediente',
      },
      {
        code: 'ing-agua-500',
        name: 'Água Mineral 500ml',
        unit: 'un',
        qty: 24,
        min: 6,
        group: 'Ingrediente',
      },
      {
        code: 'ing-hamburgueira',
        name: 'Hamburgueira (equipamento)',
        unit: 'un',
        qty: 2,
        min: 1,
        group: 'Operacional',
      },
      {
        code: 'ing-papel-toalha',
        name: 'Papel Toalha',
        unit: 'rolo',
        qty: 10,
        min: 3,
        group: 'Operacional',
      },
      {
        code: 'ing-filme-pvc',
        name: 'Plástico Filme PVC',
        unit: 'rolo',
        qty: 6,
        min: 2,
        group: 'Operacional',
      },
      { code: 'ing-tempero', name: 'Tempero', unit: 'un', qty: 15, min: 4, group: 'Operacional' },
      { code: 'ing-caneta', name: 'Caneta', unit: 'un', qty: 8, min: 2, group: 'Operacional' },
      {
        code: 'ing-saquinho',
        name: 'Saquinho de Lanche',
        unit: 'un',
        qty: 300,
        min: 60,
        group: 'Operacional',
      },
      { code: 'ing-sacola', name: 'Sacola', unit: 'un', qty: 200, min: 40, group: 'Operacional' },
      {
        code: 'ing-touca',
        name: 'Touca Descartável',
        unit: 'un',
        qty: 100,
        min: 20,
        group: 'Operacional',
      },
      {
        code: 'ing-sache-ketchup',
        name: 'Sachê de Ketchup',
        unit: 'un',
        qty: 200,
        min: 40,
        group: 'Operacional',
      },
      {
        code: 'ing-sache-mostarda',
        name: 'Sachê de Mostarda',
        unit: 'un',
        qty: 200,
        min: 40,
        group: 'Operacional',
      },
      {
        code: 'ing-sache-maionese',
        name: 'Sachê de Maionese',
        unit: 'un',
        qty: 200,
        min: 40,
        group: 'Operacional',
      },
      {
        code: 'ing-sache-extra',
        name: 'Sachê Extra',
        unit: 'un',
        qty: 200,
        min: 40,
        group: 'Operacional',
      },
      { code: 'ing-palito', name: 'Palito', unit: 'un', qty: 500, min: 100, group: 'Operacional' },
      {
        code: 'ing-guardanapos',
        name: 'Guardanapos',
        unit: 'un',
        qty: 300,
        min: 50,
        group: 'Operacional',
      },
    ]
    stockItems.forEach((si) => {
      try {
        app.findFirstRecordByData('inventory', 'code', si.code)
      } catch (_) {
        const rec = new Record(inventoryCol)
        rec.set('code', si.code)
        rec.set('name', si.name)
        rec.set('unit', si.unit)
        rec.set('qty', si.qty)
        rec.set('min', si.min)
        rec.set('group', si.group)
        app.save(rec)
      }
    })

    // 4. Helper de receitas do cardápio
    const R = {
      pao: 'ing-pao',
      paofr: 'ing-pao-frances',
      hamb: 'ing-hamburguer',
      contrafile: 'ing-contrafile',
      gourmet: 'ing-carne-gourmet',
      maxcarne: 'ing-carne-max',
      apres: 'ing-apresuntado',
      queijo: 'ing-queijo',
      cheddar: 'ing-cheddar',
      catupiry: 'ing-catupiry',
      ovo: 'ing-ovo',
      bacon: 'ing-bacon',
      calabresa: 'ing-calabresa',
      linguica: 'ing-linguica',
      filefrango: 'ing-file-frango',
      frangodesf: 'ing-frango-desfiado',
      salsicha: 'ing-salsicha',
      brocolis: 'ing-brocolis',
      maionese: 'ing-maionese',
      ketchup: 'ing-ketchup',
      mostarda: 'ing-mostarda',
      palha: 'ing-batata-palha',
      vinagrete: 'ing-vinagrete',
      alface: 'ing-alface',
      cebola: 'ing-cebola',
      tomate: 'ing-tomate',
      milho: 'ing-milho',
      maionesecasa: 'ing-maionese-casa',
      batata300: 'ing-batata-300',
      refrilata: 'ing-refri-lata',
      refri600: 'ing-refri-600',
      refri1l: 'ing-refri-1l',
      refri2l: 'ing-refri-2l',
      refri200: 'ing-refri-200',
      suco: 'ing-suco',
      agua500: 'ing-agua-500',
    }
    function rec(...keys) {
      const map = {}
      keys.forEach((k) => {
        if (k === 'molho') {
          ;['ing-maionese', 'ing-ketchup', 'ing-mostarda', 'ing-batata-palha'].forEach((id) => {
            map[id] = (map[id] || 0) + 1
          })
        } else {
          const id = R[k]
          if (id) map[id] = (map[id] || 0) + 1
        }
      })
      return Object.entries(map).map(([ingredientId, qty]) => ({ ingredientId, qty }))
    }

    const mk = (code, name, price, category, recipe) => ({ code, name, price, category, recipe })

    const menuItems = [
      // Carnes
      mk(
        'c-hamburguer',
        'Hambúrguer',
        15,
        'Carnes',
        rec('pao', 'hamb', 'apres', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
      ),
      mk(
        'c-americano',
        'Americano',
        16,
        'Carnes',
        rec('pao', 'apres', 'queijo', 'ovo', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
      ),
      mk('c-misto', 'Misto Quente', 13, 'Carnes', rec('pao', 'apres', 'queijo', 'molho')),
      mk(
        'c-bauru',
        'Bauru',
        15,
        'Carnes',
        rec('pao', 'apres', 'queijo', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
      ),
      mk('c-xburguer', 'X-Burguer', 15, 'Carnes', rec('pao', 'hamb', 'apres', 'queijo', 'molho')),
      mk(
        'c-xsalada',
        'X-Salada',
        17,
        'Carnes',
        rec('pao', 'hamb', 'apres', 'queijo', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
      ),
      mk(
        'c-xegg',
        'X-Egg',
        19,
        'Carnes',
        rec(
          'pao',
          'hamb',
          'apres',
          'ovo',
          'queijo',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'c-xcalabresa',
        'X-Calabresa',
        24,
        'Carnes',
        rec(
          'pao',
          'hamb',
          'apres',
          'calabresa',
          'queijo',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'c-xcalabresaegg',
        'X-Calabresa Egg',
        24.5,
        'Carnes',
        rec(
          'pao',
          'hamb',
          'apres',
          'calabresa',
          'ovo',
          'queijo',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'c-xbacon',
        'X-Bacon',
        24,
        'Carnes',
        rec(
          'pao',
          'hamb',
          'apres',
          'bacon',
          'queijo',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'c-xbaconegg',
        'X-Bacon Egg',
        24.5,
        'Carnes',
        rec(
          'pao',
          'hamb',
          'apres',
          'bacon',
          'ovo',
          'queijo',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'c-xtudo',
        'X-Tudo',
        26,
        'Carnes',
        rec(
          'pao',
          'hamb',
          'apres',
          'bacon',
          'queijo',
          'ovo',
          'calabresa',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'c-contrafile',
        'Contra-Filé',
        23,
        'Carnes',
        rec('pao', 'contrafile', 'apres', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
      ),
      mk(
        'c-xcontrafile',
        'X-Contra-Filé',
        25,
        'Carnes',
        rec('pao', 'contrafile', 'apres', 'queijo', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
      ),
      mk(
        'c-xcontrafileegg',
        'X-Contra-Filé Egg',
        27,
        'Carnes',
        rec(
          'pao',
          'contrafile',
          'apres',
          'queijo',
          'ovo',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'c-xcontrafilecalabresa',
        'X-Contra-Filé Calabresa',
        29,
        'Carnes',
        rec(
          'pao',
          'contrafile',
          'apres',
          'queijo',
          'calabresa',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'c-xcontrafilebacon',
        'X-Contra-Filé Bacon',
        29,
        'Carnes',
        rec(
          'pao',
          'contrafile',
          'apres',
          'queijo',
          'bacon',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'c-xcontrafilecalabresaegg',
        'X-Contra-Filé Calabresa Egg',
        29.5,
        'Carnes',
        rec(
          'pao',
          'contrafile',
          'apres',
          'queijo',
          'calabresa',
          'ovo',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'c-xcontrafilebaconegg',
        'X-Contra-Filé Bacon Egg',
        29.5,
        'Carnes',
        rec(
          'pao',
          'contrafile',
          'apres',
          'queijo',
          'bacon',
          'ovo',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'c-xcontrafiletudo',
        'X-Contra-Filé Tudo',
        32,
        'Carnes',
        rec(
          'pao',
          'contrafile',
          'apres',
          'queijo',
          'calabresa',
          'bacon',
          'ovo',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'c-max',
        'Max',
        21,
        'Carnes',
        rec('pao', 'apres', 'maxcarne', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
      ),
      mk(
        'c-xmax',
        'X Max',
        22,
        'Carnes',
        rec('pao', 'apres', 'maxcarne', 'queijo', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
      ),
      mk(
        'c-xmaxegg',
        'X Max Egg',
        23,
        'Carnes',
        rec(
          'pao',
          'apres',
          'maxcarne',
          'queijo',
          'ovo',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'c-xmaxcalabresa',
        'X Max Calabresa',
        27,
        'Carnes',
        rec(
          'pao',
          'apres',
          'maxcarne',
          'queijo',
          'calabresa',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'c-xmaxbacon',
        'X Max Bacon',
        27,
        'Carnes',
        rec(
          'pao',
          'apres',
          'maxcarne',
          'queijo',
          'bacon',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'c-xmaxcalabresaegg',
        'X Max Calabresa Egg',
        27.5,
        'Carnes',
        rec(
          'pao',
          'apres',
          'maxcarne',
          'queijo',
          'calabresa',
          'ovo',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'c-xmaxbaconegg',
        'X Max Bacon Egg',
        27.5,
        'Carnes',
        rec(
          'pao',
          'apres',
          'maxcarne',
          'queijo',
          'bacon',
          'ovo',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'c-xmaxtudo',
        'X Max Tudo',
        30,
        'Carnes',
        rec(
          'pao',
          'apres',
          'maxcarne',
          'queijo',
          'bacon',
          'calabresa',
          'ovo',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),

      // Frango
      mk(
        'f-file',
        'Filé',
        21,
        'Frango',
        rec('pao', 'filefrango', 'apres', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
      ),
      mk(
        'f-xfile',
        'X-Filé',
        22,
        'Frango',
        rec('pao', 'filefrango', 'apres', 'queijo', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
      ),
      mk(
        'f-xfileegg',
        'X-Filé Egg',
        23,
        'Frango',
        rec(
          'pao',
          'filefrango',
          'apres',
          'queijo',
          'ovo',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'f-xfilecalabresa',
        'X-Filé Calabresa',
        27,
        'Frango',
        rec(
          'pao',
          'filefrango',
          'apres',
          'queijo',
          'calabresa',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'f-xfilecalabresaegg',
        'X-Filé Calabresa Egg',
        27.5,
        'Frango',
        rec(
          'pao',
          'filefrango',
          'apres',
          'queijo',
          'calabresa',
          'ovo',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'f-xfilebacon',
        'X-Filé Bacon',
        27,
        'Frango',
        rec(
          'pao',
          'filefrango',
          'apres',
          'queijo',
          'bacon',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'f-xfilebaconegg',
        'X-Filé Bacon Egg',
        27.5,
        'Frango',
        rec(
          'pao',
          'filefrango',
          'apres',
          'queijo',
          'bacon',
          'ovo',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'f-xfiletudo',
        'X-Filé Tudo',
        29,
        'Frango',
        rec(
          'pao',
          'filefrango',
          'apres',
          'bacon',
          'queijo',
          'ovo',
          'calabresa',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'f-carijo',
        'Carijó',
        21,
        'Frango',
        rec('pao', 'frangodesf', 'apres', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
      ),
      mk(
        'f-xcarijo',
        'X-Carijó',
        23,
        'Frango',
        rec('pao', 'frangodesf', 'apres', 'queijo', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
      ),
      mk(
        'f-xcarijoegg',
        'X-Carijó Egg',
        23,
        'Frango',
        rec(
          'pao',
          'frangodesf',
          'apres',
          'queijo',
          'ovo',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'f-xcarijocalabresa',
        'X-Carijó Calabresa',
        27,
        'Frango',
        rec(
          'pao',
          'frangodesf',
          'apres',
          'queijo',
          'calabresa',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'f-xcarijocalabresaegg',
        'X-Carijó Calabresa Egg',
        27.5,
        'Frango',
        rec(
          'pao',
          'frangodesf',
          'apres',
          'queijo',
          'calabresa',
          'ovo',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'f-xcarijobacon',
        'X-Carijó Bacon',
        27,
        'Frango',
        rec(
          'pao',
          'frangodesf',
          'apres',
          'queijo',
          'bacon',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'f-xcarijobaconegg',
        'X-Carijó Bacon Egg',
        27.5,
        'Frango',
        rec(
          'pao',
          'frangodesf',
          'apres',
          'queijo',
          'bacon',
          'ovo',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'f-xcarijotudo',
        'X-Carijó Tudo',
        29,
        'Frango',
        rec(
          'pao',
          'frangodesf',
          'apres',
          'queijo',
          'bacon',
          'ovo',
          'calabresa',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),

      // Hot-Dog
      mk(
        'h-hotdog',
        'Hotdog',
        15,
        'Hot-Dog',
        rec('pao', 'salsicha', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
      ),
      mk(
        'h-xhotdog',
        'X-Hotdog',
        17,
        'Hot-Dog',
        rec('pao', 'salsicha', 'queijo', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
      ),
      mk(
        'h-xhotdogegg',
        'X-Hotdog Egg',
        19,
        'Hot-Dog',
        rec('pao', 'salsicha', 'queijo', 'ovo', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
      ),
      mk(
        'h-xhotdogbacon',
        'X-Hotdog Bacon',
        24,
        'Hot-Dog',
        rec('pao', 'salsicha', 'bacon', 'queijo', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
      ),
      mk(
        'h-xhotdogbaconegg',
        'X-Hotdog Bacon Egg',
        24.5,
        'Hot-Dog',
        rec(
          'pao',
          'salsicha',
          'bacon',
          'ovo',
          'queijo',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'h-xhotdogcalabresa',
        'X-Hotdog Calabresa',
        24,
        'Hot-Dog',
        rec(
          'pao',
          'salsicha',
          'calabresa',
          'queijo',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'h-xhotdogcalabresaegg',
        'X-Hotdog Calabresa Egg',
        24.5,
        'Hot-Dog',
        rec(
          'pao',
          'salsicha',
          'calabresa',
          'ovo',
          'queijo',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'h-xhotdogtudo',
        'X-Hotdog Tudo',
        26,
        'Hot-Dog',
        rec(
          'pao',
          'salsicha',
          'bacon',
          'ovo',
          'calabresa',
          'queijo',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),

      // Gourmet
      mk(
        'g-hamburguergourmet',
        'Hambúrguer Gourmet',
        22,
        'Gourmet',
        rec('pao', 'gourmet', 'apres', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
      ),
      mk(
        'g-xburguergourmet',
        'X-Burguer Gourmet',
        22,
        'Gourmet',
        rec('pao', 'gourmet', 'apres', 'queijo', 'molho'),
      ),
      mk(
        'g-xsaladagourmet',
        'X-Salada Gourmet',
        24,
        'Gourmet',
        rec('pao', 'gourmet', 'apres', 'queijo', 'molho', 'alface', 'cebola', 'tomate', 'milho'),
      ),
      mk(
        'g-xegggourmet',
        'X-Egg Gourmet',
        26,
        'Gourmet',
        rec(
          'pao',
          'gourmet',
          'apres',
          'ovo',
          'queijo',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'g-xcalabresagourmet',
        'X-Calabresa Gourmet',
        29,
        'Gourmet',
        rec(
          'pao',
          'gourmet',
          'apres',
          'calabresa',
          'queijo',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'g-xcalabresaegggourmet',
        'X-Calabresa Egg Gourmet',
        29.5,
        'Gourmet',
        rec(
          'pao',
          'gourmet',
          'apres',
          'calabresa',
          'ovo',
          'queijo',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'g-xbacongourmet',
        'X-Bacon Gourmet',
        29,
        'Gourmet',
        rec(
          'pao',
          'gourmet',
          'apres',
          'bacon',
          'queijo',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'g-xbaconegggourmet',
        'X-Bacon Egg Gourmet',
        29.5,
        'Gourmet',
        rec(
          'pao',
          'gourmet',
          'apres',
          'bacon',
          'ovo',
          'queijo',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'g-xtudogourmet',
        'X-Tudo Gourmet',
        32,
        'Gourmet',
        rec(
          'pao',
          'gourmet',
          'apres',
          'bacon',
          'queijo',
          'ovo',
          'calabresa',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),
      mk(
        'e-especialgourmet',
        'Especial Gourmet',
        45,
        'Gourmet',
        rec(
          'pao',
          'gourmet',
          'gourmet',
          'apres',
          'queijo',
          'queijo',
          'bacon',
          'ovo',
          'ovo',
          'calabresa',
          'catupiry',
          'cheddar',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),

      // Especial
      mk(
        'e-xbrocolis',
        'X-Brócolis (com Bacon)',
        24,
        'Especial',
        rec('pao', 'bacon', 'brocolis', 'queijo', 'catupiry', 'molho'),
      ),
      mk(
        'h-paolinguica',
        'Pão c/ Linguiça',
        22,
        'Especial',
        rec(
          'pao',
          'linguica',
          'linguica',
          'queijo',
          'maionesecasa',
          'vinagrete',
          'alface',
          'cebola',
          'tomate',
          'milho',
        ),
      ),

      // Combos
      mk(
        'combo-ind1',
        'Combo Individual 01 — X-Tudo + Batata + Refri Lata',
        50,
        'Combos',
        rec(
          'pao',
          'hamb',
          'apres',
          'bacon',
          'queijo',
          'ovo',
          'calabresa',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
          'batata300',
          'refrilata',
        ),
      ),
      mk(
        'combo-ind2',
        'Combo Individual 02 — X-Bacon + Batata + Refri Lata',
        49,
        'Combos',
        rec(
          'pao',
          'hamb',
          'apres',
          'bacon',
          'queijo',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
          'batata300',
          'refrilata',
        ),
      ),
      mk(
        'combo-casal1',
        'Combo Casal 01 — 2 X-Tudo + Batata + Refri 1L',
        75,
        'Combos',
        rec(
          'pao',
          'pao',
          'hamb',
          'hamb',
          'apres',
          'apres',
          'bacon',
          'bacon',
          'queijo',
          'queijo',
          'ovo',
          'ovo',
          'calabresa',
          'calabresa',
          'molho',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
          'alface',
          'cebola',
          'tomate',
          'milho',
          'batata300',
          'refri1l',
        ),
      ),
      mk(
        'combo-casal2',
        'Combo Casal 02 — 2 X-Bacon + Batata + Refri 1L',
        73,
        'Combos',
        rec(
          'pao',
          'pao',
          'hamb',
          'hamb',
          'apres',
          'apres',
          'bacon',
          'bacon',
          'queijo',
          'queijo',
          'molho',
          'molho',
          'alface',
          'cebola',
          'tomate',
          'milho',
          'alface',
          'cebola',
          'tomate',
          'milho',
          'batata300',
          'refri1l',
        ),
      ),
      mk(
        'combo-infantil',
        'Combo Infantil — X-Burguer + Batata + Refri 200ml',
        33,
        'Combos',
        rec('pao', 'hamb', 'apres', 'queijo', 'molho', 'batata300', 'refri200'),
      ),

      // Bebidas
      mk('b-refri2l', 'Refrigerante 2L (genérico)', 10, 'Bebidas', rec('refri2l')),
      mk(
        'b-refri2lmarca',
        'Refrigerante 2L (Coca, Fanta, Sprite, Antártica)',
        15,
        'Bebidas',
        rec('refri2l'),
      ),
      mk('b-refri600', 'Refrigerante 600ml', 8, 'Bebidas', rec('refri600')),
      mk('b-refri1l', 'Refrigerante 1L', 10, 'Bebidas', rec('refri1l')),
      mk('b-refrilata', 'Refrigerante Lata', 6, 'Bebidas', rec('refrilata')),
      mk('b-suco', 'Suco Tropical', 8, 'Bebidas', rec('suco')),
      mk('b-agua500', 'Água Mineral 500ml', 3, 'Bebidas', rec('agua500')),

      // Complementos
      mk('x-catupiry', 'Catupiry (adicional)', 4, 'Complementos', rec('catupiry')),
      mk('x-cheddar', 'Cheddar (adicional)', 3, 'Complementos', rec('cheddar')),
      mk('x-ovo', 'Ovo (adicional)', 3, 'Complementos', rec('ovo')),
      mk('x-queijo', 'Queijo (adicional)', 4, 'Complementos', rec('queijo')),
      mk('x-presunto', 'Presunto (adicional)', 3, 'Complementos', rec('apres')),
      mk('x-filefrango', 'Filé de Frango (adicional)', 10, 'Complementos', rec('filefrango')),
      mk('x-frangodesf', 'Frango Desfiado (adicional)', 10, 'Complementos', rec('frangodesf')),
      mk('x-carne', 'Carne (adicional)', 3, 'Complementos', rec('hamb')),
      mk('x-contrafile', 'Contra-Filé (adicional)', 10, 'Complementos', rec('contrafile')),
      mk('x-carnegourmet', 'Carne Gourmet (adicional)', 10, 'Complementos', rec('gourmet')),
      mk('x-paofrances', 'Pão Francês (unidade)', 2, 'Complementos', rec('paofr')),
    ]

    const menuCol = app.findCollectionByNameOrId('menu')
    menuItems.forEach((mi) => {
      try {
        app.findFirstRecordByData('menu', 'code', mi.code)
      } catch (_) {
        const rec = new Record(menuCol)
        rec.set('code', mi.code)
        rec.set('name', mi.name)
        rec.set('price', mi.price)
        rec.set('category', mi.category)
        rec.set('active', true)
        rec.set('recipe', mi.recipe)
        app.save(rec)
      }
    })

    // 5. Seed sample orders (balcão e online) se orders estiver vazia
    const ordersCol = app.findCollectionByNameOrId('orders')
    if (app.countRecords('orders') === 0) {
      const sampleOrders = [
        {
          ticketNumber: 1,
          items: [
            { name: 'X-Tudo', price: 26, qty: 1, removed: [], added: [] },
            { name: 'Refrigerante Lata', price: 6, qty: 1, removed: [], added: [] },
          ],
          subtotal: 32,
          discount: 0,
          deliveryFee: 0,
          total: 32,
          payment: 'Dinheiro',
          status: 'concluído',
          origin: 'balcao',
        },
        {
          ticketNumber: 2,
          items: [
            {
              name: 'X-Bacon',
              price: 24,
              qty: 1,
              removed: ['Cebola'],
              added: [{ name: 'Queijo Mussarela', qty: 1 }],
            },
            { name: 'Água Mineral 500ml', price: 3, qty: 1, removed: [], added: [] },
          ],
          subtotal: 31,
          discount: 0,
          deliveryFee: 0,
          total: 31,
          payment: 'Pix',
          status: 'concluído',
          origin: 'balcao',
        },
        {
          ticketNumber: 3,
          items: [
            {
              name: 'Combo Casal 01 — 2 X-Tudo + Batata + Refri 1L',
              price: 75,
              qty: 1,
              removed: [],
              added: [],
            },
          ],
          subtotal: 75,
          discount: 0,
          deliveryFee: 7,
          total: 82,
          payment: 'Pix',
          status: 'pendente',
          origin: 'online',
          customerName: 'Mariana Silva',
          customerPhone: '12999998888',
          deliveryType: 'entrega',
          customerAddress: 'Rua das Palmeiras, 145, Araretama',
        },
        {
          ticketNumber: 4,
          items: [
            { name: 'Hambúrguer Gourmet', price: 22, qty: 2, removed: [], added: [] },
            { name: 'Refrigerante 600ml', price: 8, qty: 1, removed: [], added: [] },
          ],
          subtotal: 52,
          discount: 2,
          deliveryFee: 0,
          total: 50,
          payment: 'Cartão',
          status: 'aceito',
          origin: 'online',
          customerName: 'Lucas Ferreira',
          customerPhone: '12988887777',
          deliveryType: 'retirada',
        },
      ]

      sampleOrders.forEach((so) => {
        const o = new Record(ordersCol)
        o.set('ticketNumber', so.ticketNumber)
        o.set('items', so.items)
        o.set('subtotal', so.subtotal)
        o.set('discount', so.discount)
        o.set('deliveryFee', so.deliveryFee)
        o.set('total', so.total)
        o.set('payment', so.payment)
        o.set('status', so.status)
        o.set('origin', so.origin)
        if (so.customerName) o.set('customerName', so.customerName)
        if (so.customerPhone) o.set('customerPhone', so.customerPhone)
        if (so.deliveryType) o.set('deliveryType', so.deliveryType)
        if (so.customerAddress) o.set('customerAddress', so.customerAddress)
        app.save(o)
      })

      // Ajustar ticket_counter para 5
      try {
        const tc = app.findFirstRecordByData('settings', 'key', 'ticket_counter')
        tc.set('value', '5')
        app.save(tc)
      } catch (_) {}
    }
  },
  (app) => {},
)
