import React, { useEffect, useRef, useState } from 'react'
import { Map, Plus, Trash2, Save } from 'lucide-react'
import pb from '@/lib/pocketbase/client'
import type { DeliveryFeeItem } from '@/lib/geoDistance'

type Zone = DeliveryFeeItem & { polygon?: [number,number][]; active?: boolean }

export default function DeliveryFeeZones(){
 const [zones,setZones]=useState<Zone[]>([]),[open,setOpen]=useState(false),[name,setName]=useState(''),[fee,setFee]=useState(0),[points,setPoints]=useState<[number,number][]>([])
 const mapEl=useRef<HTMLDivElement|null>(null), mapRef=useRef<any>(null), layerRef=useRef<any>(null)
 const load=()=>pb.collection('delivery_fees').getFullList<Zone>({sort:'name'}).then(setZones).catch(()=>setZones([]))
 useEffect(()=>{load()},[])
 useEffect(()=>{if(!open)return;let alive=true;const boot=async()=>{if(!(window as any).L){if(!document.getElementById('leaflet-css')){const l=document.createElement('link');l.id='leaflet-css';l.rel='stylesheet';l.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';document.head.appendChild(l)}await new Promise<void>((res,rej)=>{const s=document.createElement('script');s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';s.onload=()=>res();s.onerror=rej;document.body.appendChild(s)})}if(!alive||!mapEl.current)return;const L=(window as any).L;if(mapRef.current)mapRef.current.remove();const m=L.map(mapEl.current).setView([-22.92,-45.46],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap'}).addTo(m);m.on('click',(e:any)=>setPoints(p=>[...p,[e.latlng.lat,e.latlng.lng]]));mapRef.current=m};boot();return()=>{alive=false}},[open])
 useEffect(()=>{const L=(window as any).L,m=mapRef.current;if(!L||!m)return;if(layerRef.current)m.removeLayer(layerRef.current);if(points.length){layerRef.current=L.polygon(points,{color:'#E10600'}).addTo(m)}},[points])
 const save=async()=>{if(!name.trim()||fee<0||points.length<3)return alert('Informe nome, taxa e marque pelo menos 3 pontos no mapa.');const center=points.reduce((a,p)=>[a[0]+p[0]/points.length,a[1]+p[1]/points.length] as [number,number],[0,0] as [number,number]);try{await pb.collection('delivery_fees').create({name:name.trim(),fee,lat:center[0],lng:center[1],description:JSON.stringify({polygon:points,active:true})});setName('');setFee(0);setPoints([]);setOpen(false);load()}catch(e:any){alert(e?.message||'Não foi possível cadastrar a região.')}} 
 return <><div className="rounded-xl border border-[#27272A] bg-[#121215] p-4"><span className="block text-[11px] font-semibold uppercase text-zinc-500">Taxas por região</span><div className="mt-2 flex gap-2"><button onClick={()=>setOpen(true)} className="flex items-center gap-1 rounded-lg bg-[#E10600] px-3 py-2 text-xs font-bold text-white"><Plus size={13}/>Cadastrar taxa</button><button onClick={()=>setOpen(true)} className="flex items-center gap-1 rounded-lg border border-zinc-700 px-3 py-2 text-xs font-bold text-white"><Map size={13}/>Abrir mapa</button></div><div className="mt-2 text-[10px] text-zinc-500">{zones.length} região(ões) cadastrada(s)</div></div>
 {open&&<div className="fixed inset-0 z-[70] flex items-center justify-center bg-black/85 p-4" onClick={()=>setOpen(false)}><div className="w-full max-w-4xl rounded-2xl border border-zinc-700 bg-[#121215] p-5" onClick={e=>e.stopPropagation()}><div className="mb-3 flex justify-between"><div><h3 className="font-bold text-white">Mapa de taxas de entrega</h3><p className="text-xs text-zinc-400">Clique no mapa contornando a região. O polígono será usado para definir a taxa.</p></div><button onClick={()=>setOpen(false)} className="text-zinc-400">✕</button></div><div className="grid gap-3 md:grid-cols-[1fr_280px]"><div ref={mapEl} className="h-[430px] rounded-xl"/><div className="space-y-3"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome da região" className="w-full rounded-lg border border-zinc-700 bg-zinc-950 p-2 text-xs text-white"/><input type="number" min="0" step=".5" value={fee} onChange={e=>setFee(Number(e.target.value))} placeholder="Taxa R$" className="w-full rounded-lg border border-zinc-700 bg-zinc-950 p-2 text-xs text-white"/><div className="text-xs text-zinc-400">{points.length} pontos demarcados</div><button onClick={()=>setPoints([])} className="flex w-full items-center justify-center gap-1 rounded-lg border border-zinc-700 p-2 text-xs text-zinc-300"><Trash2 size={13}/>Limpar desenho</button><button onClick={save} className="flex w-full items-center justify-center gap-1 rounded-lg bg-emerald-600 p-2 text-xs font-bold text-white"><Save size={13}/>Salvar região e taxa</button></div></div></div></div>}</>
}
